### ISSUE TITLE
你好作者，请问您只使用SeLSTM时的结果如何

### ISSUE THREAD

**Issue by xzc19980125** [ShuGuoJ/SSLstm#2]
请问您只使用SeLSTM时的结果如何，我在针对KSC数据集使用TrainBySpectra时得到的结果很差，loss一直在2.5以上，达不到文章的效果，请问您的结果如何？如果有较好的结果，可否问一下具体的参数设置是怎样的？

**Comment by ShuGuoJ** [comment]
I have seen our experimental results. In some splitting, it works very well, while it works badly in other splitting.

**Comment by xzc19980125** [comment]
Thank you for your reply. So, you mean that the results are related to the splitting of dataset, right ?

**Comment by ShuGuoJ** [comment]
Yes. And it is also related to the patch size. A smaller size is preferable.

**Comment by xzc19980125** [comment]
I will try again to get better results. Thank you for answering my questions.
